# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Material UI testing and linting

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: yarn install
      
    - name: Lint
      run: yarn lint
    - name: Build test  
      run: |
        yarn bundle
        yarn build
