name: Publish component set on acceptance

on:
  push:
    branches:
      - acceptance

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: yarn install

      - name: build
        run: yarn build

      - name: bundle
        run: yarn bundle

      - name: upload
        env:
          AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_ACCEPTANCE }}
          AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_ACCEPTANCE }}
        run: yarn upload
      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v2
        with:
          name: 'Bettyblocks release bot'
          email: 'bettyblocks-release@bettyblocks.com'
          actor: 'BettyblocksReleaseBot'
          token: '${{ secrets.GH_TOKEN }}'
      - name: release notes
        run: npx semantic-release