name: Publish component set on test environments

on:
  push:
    branches:
      - edge

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: yarn install

      - name: build
        run: yarn build

      - name: bundle
        run: yarn bundle

      - name: upload
        run: yarn upload